"""Pydantic v2 schemas for the AI Model Critic service."""

from __future__ import annotations

from enum import Enum
from typing import Any, List
from pydantic import BaseModel, ConfigDict, Field, field_validator


class CritiqueGrade(str, Enum):
    """The allowed grade choices for critique reviews."""

    A_PLUS = "A+"
    A = "A"
    A_MINUS = "A-"
    B_PLUS = "B+"
    B = "B"
    B_MINUS = "B-"
    C = "C"
    D = "D"
    F = "F"


def _clean_string(field_name: str, v: Any) -> str:
    """Strip whitespace and check string is non-empty."""
    if not isinstance(v, str):
        raise ValueError(f"{field_name} must be a string")
    cleaned = v.strip()
    if not cleaned:
        raise ValueError(f"{field_name} cannot be empty or whitespace-only")
    return cleaned


class ModelCritique(BaseModel):
    """Structured report critique generated by the AI Model Critic."""

    model_config = ConfigDict(use_enum_values=True)

    critique_id: str = Field(..., description="Unique ID for this critique run.")
    report_id: str = Field(..., description="Linkage ID to the analyzed ExecutionReport.")
    overall_grade: CritiqueGrade = Field(..., description="ML Engineer overall grade card.")
    production_ready: bool = Field(..., description="Whether model is verified safe for production.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence rating from 0.0 to 1.0.")
    strengths: List[str] = Field(..., description="Key strengths identified.")
    weaknesses: List[str] = Field(..., description="Key weaknesses identified.")
    risks: List[str] = Field(..., description="High priority risks identified.")
    recommendations: List[str] = Field(..., description="Constructive ML engineer recommendations.")
    warnings: List[str] = Field(..., description="Important warnings or notes.")
    summary: str = Field(..., description="High-level evaluation executive summary.")

    @field_validator("critique_id", "report_id", "summary", mode="before")
    @classmethod
    def _validate_non_empty_strings(cls, v: Any, info: Any) -> str:
        return _clean_string(info.field_name, v)

    @field_validator("strengths", "weaknesses", "risks", "recommendations", "warnings", mode="before")
    @classmethod
    def _validate_lists(cls, v: Any, info: Any) -> List[str]:
        if not isinstance(v, list):
            raise ValueError(f"{info.field_name} must be a list")
        cleaned = []
        for i, item in enumerate(v):
            item_clean = _clean_string(f"{info.field_name}[{i}]", item)
            cleaned.append(item_clean)
        return cleaned
