"""AI provider factory and adapters for DeployAI.

Stage 8B resolves validated configuration models into concrete,
non-networking adapter representations of the AIProvider contract.
"""

from __future__ import annotations

from typing import Any

from backend.app.ai_planning.providers.base import AIProvider, AIProviderError
from backend.app.ai_providers.schemas import (
    AIProviderStatus,
    OllamaProviderConfig,
    OpenAICompatibleProviderConfig,
    AIProviderSettings,
)


class AIProviderFactoryError(Exception):
    """Exception raised when provider factory resolution or construction constraints are violated."""
    pass


class OllamaAIProvider(AIProvider):
    """Adapter for a local Ollama AI provider.

    Keeps configuration validated inside OllamaProviderConfig and implements
    the abstract AIProvider interface without conducting network requests.
    """

    def __init__(self, config: OllamaProviderConfig) -> None:
        """Initialize with validated configuration.

        Args:
            config: Validated Ollama configuration schema.
        """
        self._config = config

    @property
    def config(self) -> OllamaProviderConfig:
        """Get the stored configuration object."""
        return self._config

    def generate(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """Generate a text completion from the local Ollama provider service.

        Args:
            system_prompt: System-level instructions for the AI model.
            user_prompt: User-level content / context for the AI model.

        Returns:
            The stripped raw assistant text generated by the model.

        Raises:
            AIProviderError: If prompts are invalid, the request fails, times out,
                or a malformed response is returned.
        """
        if not isinstance(system_prompt, str):
            raise AIProviderError("system_prompt must be a string")
        if not isinstance(user_prompt, str):
            raise AIProviderError("user_prompt must be a string")

        if not system_prompt.strip():
            raise AIProviderError("system_prompt cannot be empty or whitespace-only")
        if not user_prompt.strip():
            raise AIProviderError("user_prompt cannot be empty or whitespace-only")

        import httpx
        url = self._config.base_url + "/api/chat"
        payload = {
            "model": self._config.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "format": "json",
            "stream": False
        }
        timeout = self._config.request_timeout_seconds

        try:
            response = httpx.post(url, json=payload, timeout=timeout)
            response.raise_for_status()
        except httpx.ConnectError as exc:
            raise AIProviderError("Failed to connect to Ollama provider.") from exc
        except httpx.TimeoutException as exc:
            raise AIProviderError("Ollama request timed out.") from exc
        except httpx.HTTPStatusError as exc:
            raise AIProviderError(f"Ollama provider returned HTTP {exc.response.status_code}.") from exc
        except httpx.RequestError as exc:
            raise AIProviderError("General request error contacting Ollama provider.") from exc
        except Exception as exc:
            raise AIProviderError(f"Unexpected transport failure: {exc}") from exc

        try:
            response_json = response.json()
        except Exception as exc:
            raise AIProviderError("Response body is not valid JSON.") from exc

        if not isinstance(response_json, dict):
            raise AIProviderError("Top-level JSON value is not an object/dict.")

        if "message" not in response_json:
            raise AIProviderError("Response JSON is missing 'message' key.")

        message = response_json["message"]
        if not isinstance(message, dict):
            raise AIProviderError("'message' key is not an object/dict.")

        if "content" not in message:
            raise AIProviderError("Response message JSON is missing 'content' key.")

        content = message["content"]
        if not isinstance(content, str):
            raise AIProviderError("'content' must be a string.")

        stripped_content = content.strip()
        if not stripped_content:
            raise AIProviderError("'content' cannot be empty or whitespace-only.")

        return stripped_content


class OpenAICompatibleAIProvider(AIProvider):
    """Adapter for a remote OpenAI-compatible AI provider.

    Keeps configuration validated inside OpenAICompatibleProviderConfig and
    implements the abstract AIProvider interface by sending synchronous HTTP
    requests to the configured OpenAI-compatible chat completions endpoint.
    """

    def __init__(self, config: OpenAICompatibleProviderConfig) -> None:
        """Initialize with validated configuration.

        Args:
            config: Validated OpenAI-compatible configuration schema.
        """
        self._config = config

    @property
    def config(self) -> OpenAICompatibleProviderConfig:
        """Get the stored configuration object."""
        return self._config

    def generate(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """Generate a text completion from the OpenAI-compatible provider service.

        Args:
            system_prompt: System-level instructions for the AI model.
            user_prompt: User-level content / context for the AI model.

        Returns:
            The stripped raw assistant text generated by the model.

        Raises:
            AIProviderError: If prompts are invalid, the request fails, times out,
                or a malformed response is returned.
        """
        if not isinstance(system_prompt, str):
            raise AIProviderError("system_prompt must be a string")
        if not isinstance(user_prompt, str):
            raise AIProviderError("user_prompt must be a string")

        if not system_prompt.strip():
            raise AIProviderError("system_prompt cannot be empty or whitespace-only")
        if not user_prompt.strip():
            raise AIProviderError("user_prompt cannot be empty or whitespace-only")

        import httpx
        url = self._config.base_url + "/chat/completions"
        payload = {
            "model": self._config.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "stream": False
        }
        timeout = self._config.request_timeout_seconds

        headers: dict[str, str] = {}
        if self._config.api_key is not None:
            headers["Authorization"] = f"Bearer {self._config.api_key}"

        try:
            response = httpx.post(url, json=payload, timeout=timeout, headers=headers)
            response.raise_for_status()
        except httpx.ConnectError as exc:
            raise AIProviderError("Failed to connect to OpenAI-compatible provider.") from exc
        except httpx.TimeoutException as exc:
            raise AIProviderError("OpenAI-compatible provider request timed out.") from exc
        except httpx.HTTPStatusError as exc:
            raise AIProviderError(f"OpenAI-compatible provider returned HTTP {exc.response.status_code}.") from exc
        except httpx.RequestError as exc:
            raise AIProviderError("General request error contacting OpenAI-compatible provider.") from exc
        except Exception as exc:
            raise AIProviderError(f"Unexpected transport failure: {exc}") from exc

        try:
            response_json = response.json()
        except Exception as exc:
            raise AIProviderError("Response body is not valid JSON.") from exc

        if not isinstance(response_json, dict):
            raise AIProviderError("Top-level JSON value is not an object/dict.")

        if "choices" not in response_json:
            raise AIProviderError("Response JSON is missing 'choices' key.")

        choices = response_json["choices"]
        if not isinstance(choices, list):
            raise AIProviderError("'choices' is not a list.")

        if len(choices) == 0:
            raise AIProviderError("'choices' list is empty.")

        first_choice = choices[0]
        if not isinstance(first_choice, dict):
            raise AIProviderError("First choice is not an object/dict.")

        if "message" not in first_choice:
            raise AIProviderError("First choice is missing 'message' key.")

        message = first_choice["message"]
        if not isinstance(message, dict):
            raise AIProviderError("'message' is not an object/dict.")

        if "content" not in message:
            raise AIProviderError("Response message is missing 'content' key.")

        content = message["content"]
        if not isinstance(content, str):
            raise AIProviderError("'content' must be a string.")

        stripped_content = content.strip()
        if not stripped_content:
            raise AIProviderError("'content' cannot be empty or whitespace-only.")

        return stripped_content


class AIProviderFactory:
    """Factory for resolving configuration objects into executable provider boundaries."""

    @staticmethod
    def create(config: Any) -> AIProvider:
        """Create an AIProvider adapter from a validated configuration schema.

        Args:
            config: A validated OllamaProviderConfig or OpenAICompatibleProviderConfig.

        Returns:
            The constructed AIProvider instance matching the configuration type.

        Raises:
            AIProviderFactoryError: If the input is not a valid configuration model,
                or if the configuration is disabled.
        """
        if config is None:
            raise AIProviderFactoryError("Configuration cannot be None.")

        # Rejects dicts, raw strings, arbitrary objects, or base models
        if not isinstance(config, (OllamaProviderConfig, OpenAICompatibleProviderConfig)):
            raise AIProviderFactoryError(
                f"Unsupported configuration type: {type(config).__name__}. "
                "Must be a validated OllamaProviderConfig or OpenAICompatibleProviderConfig instance."
            )

        if not config.enabled:
            raise AIProviderFactoryError(
                f"Cannot construct provider for disabled configuration '{config.config_id}'."
            )

        if isinstance(config, OllamaProviderConfig):
            return OllamaAIProvider(config)
        else:
            return OpenAICompatibleAIProvider(config)

    @staticmethod
    def create_active(settings: Any) -> AIProvider:
        """Resolve and construct the active provider specified in the global settings.

        Args:
            settings: User-configured global AIProviderSettings.

        Returns:
            The resolved and constructed active AIProvider instance.

        Raises:
            AIProviderFactoryError: If the settings parameter is invalid, status is
                unconfigured, active_config_id is missing, or the active configuration
                cannot be found or is disabled.
        """
        if not isinstance(settings, AIProviderSettings):
            raise AIProviderFactoryError(
                f"Invalid settings input type: {type(settings).__name__}. "
                "Must be an instance of AIProviderSettings."
            )

        if settings.status != AIProviderStatus.CONFIGURED:
            raise AIProviderFactoryError(
                f"Settings status is '{settings.status.value}'. An active provider "
                "can only be created from a 'configured' settings object."
            )

        if settings.active_config_id is None:
            raise AIProviderFactoryError(
                "active_config_id is not specified in the configuration settings."
            )

        active_config = None
        for config in settings.providers:
            if config.config_id == settings.active_config_id:
                active_config = config
                break

        if active_config is None:
            raise AIProviderFactoryError(
                f"Active configuration ID '{settings.active_config_id}' was not found "
                "in the configured providers list."
            )

        # Ensure active is enabled (redundant check but mandated by stage safety guidelines)
        if not active_config.enabled:
            raise AIProviderFactoryError(
                f"The resolved active provider configuration '{settings.active_config_id}' "
                "is disabled."
            )

        return AIProviderFactory.create(active_config)


def detect_ai_provider() -> AIProvider | None:
    """Detects running Ollama services or Groq/OpenAI environment keys.
    Returns the appropriate AIProvider instance or None if not configured.
    """
    import os
    import httpx
    from backend.app.ai_providers.schemas import OllamaProviderConfig, OpenAICompatibleProviderConfig

    # 1. Check local Ollama service
    ollama_url = "http://localhost:11434"
    try:
        response = httpx.get(f"{ollama_url}/api/tags", timeout=1)
        if response.status_code == 200:
            models_data = response.json()
            models_list = models_data.get("models", [])
            if models_list:
                selected_model = models_list[0]["name"]
                config = OllamaProviderConfig(
                    config_id="auto-ollama",
                    display_name="Auto Ollama",
                    model_name=selected_model,
                    base_url=ollama_url,
                    request_timeout_seconds=600.0
                )
                return OllamaAIProvider(config)
    except Exception:
        pass

    # 2. Check Groq API key
    groq_key = os.getenv("GROQ_API_KEY")
    if groq_key and groq_key != "mock" and groq_key != "mock_key":
        config = OpenAICompatibleProviderConfig(
            config_id="auto-groq",
            display_name="Auto Groq",
            model_name="llama-3.1-8b-instant",
            base_url="https://api.groq.com/openai/v1",
            api_key=groq_key
        )
        return OpenAICompatibleAIProvider(config)

    # 3. Check OpenAI API key
    openai_key = os.getenv("OPENAI_API_KEY")
    if openai_key:
        config = OpenAICompatibleProviderConfig(
            config_id="auto-openai",
            display_name="Auto OpenAI",
            model_name="gpt-4o-mini",
            base_url="https://api.openai.com/v1",
            api_key=openai_key
        )
        return OpenAICompatibleAIProvider(config)

    return None

